{{- if .Values.certManager.enabled -}}
{{- if not .Values.certManager.issuerRef -}}
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "k8s-image-swapper.fullname". }}-self-signed-issuer
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "k8s-image-swapper.fullname". }}-root-cert
spec:
  secretName: {{ template "k8s-image-swapper.fullname". }}-root-cert
  duration: 43800h0m0s # 5y
  issuerRef:
    name: {{ template "k8s-image-swapper.fullname". }}-self-signed-issuer
  commonName: "ca.webhook.k8s-image-swapper"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "k8s-image-swapper.fullname". }}-root-issuer
spec:
  ca:
    secretName: {{ template "k8s-image-swapper.fullname". }}-root-cert
{{- end }}
---
# generate a serving certificate for the apiservices to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "k8s-image-swapper.fullname". }}
spec:
  secretName: {{ template "k8s-image-swapper.fullname". }}
  duration: 8760h0m0s # 1y
  issuerRef:
    {{- if .Values.certManager.issuerRef }}
    {{- toYaml .Values.certManager.issuerRef | nindent 4 }}
    {{- else }}
    name: {{ template "k8s-image-swapper.fullname". }}-root-issuer
    {{- end }}
  dnsNames:
  - {{ template "k8s-image-swapper.fullname". }}
  - {{ template "k8s-image-swapper.fullname". }}.{{ .Release.Namespace }}
  - {{ template "k8s-image-swapper.fullname". }}.{{ .Release.Namespace }}.svc
{{- end -}}
